#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : mkfontscale
Version  : 1.1.3
Release  : 9
URL      : https://xorg.freedesktop.org/releases/individual/app/mkfontscale-1.1.3.tar.gz
Source0  : https://xorg.freedesktop.org/releases/individual/app/mkfontscale-1.1.3.tar.gz
Source99 : https://xorg.freedesktop.org/releases/individual/app/mkfontscale-1.1.3.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mkfontscale-bin
Requires: mkfontscale-doc
BuildRequires : pkgconfig(fontenc)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
mkfontscale creates the fonts.scale and fonts.dir index files used by the
legacy X11 font system.

%package bin
Summary: bin components for the mkfontscale package.
Group: Binaries

%description bin
bin components for the mkfontscale package.


%package doc
Summary: doc components for the mkfontscale package.
Group: Documentation

%description doc
doc components for the mkfontscale package.


%prep
%setup -q -n mkfontscale-1.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522112175
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1522112175
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mkfontscale

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
